# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 69e05b9aaafc23592cae8e7b9e7ccfe5175185768c4884990c8eb35481d11dc0abe22481026fd4610a805f771c0e5b8d96e817e374a73835b89cdaf902677616

test:
  secret_key_base: 2ae43332d5670494c8ca7c1e54b9268a83744a9ac2d9ea8947f782e4fb7b851bdfc7cbd9d6af90c0e36dcd96a2fa6f2a2f68158d7b5eb979bd932dc299a53414

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
